#!/bin/sh
#
# 此脚本用于在确认路由器已经成功启动后，执行用户自定义脚本列表
#
logger -st "($(basename $0))" $$ "***** RUN USER'S CUSTOM SCRIPTS IN USB FLASH DRIVE *****"
#
# Check if the router is ready for running user's custom scripts
# 检查路由器是否已经准备好执行用户自定义脚本
#
# Check it out every 30 seconds in 5 minutes.
# 每30秒检查1次，最多执行10次，最多用时5分钟
i=1
while [ $i -le 10 ]
do
    success_start_service=`nvram get success_start_service`
    if [ "$success_start_service" == "1" ]
    then
        logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS READY *****"
        break
    fi
    i=$(($i+1))
    logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS NOT READY, WAIT 30 SECONDS MORE *****"
    sleep 30
done
#
# Stop and Exit
# 如果10次检查均为路由器没准备好执行脚本，则该脚本终止
if [ "$success_start_service" != "1" ]
then
    logger -st "($(basename $0))" $$ "***** ASUS ROUTER IS NOT READY *****"
    logger -st "($(basename $0))" $$ "***** EXIT *****"
    exit 1
fi
#
# Check if /tmp/mnt/sda1/scripts/userscripts exists
# 检查用户自定义脚本列表（本例中，该脚本为/tmp/mnt/sda1/scripts/userscripts exists）是否存在
if [ -e "/tmp/mnt/sda1/scripts/userscripts" ]
then
    logger -st "($(basename $0))" $$ "***** LIST OF USER'S CUSTOM SCRIPTS EXISTS *****"
    # Load user's custom scripts
    # 如果用户自定义脚本列表存在，则执行该脚本
    logger -st "($(basename $0))" $$ "***** LOAD USER'S CUSTOM SCRIPTS *****"
    /tmp/mnt/sda1/scripts/userscripts
else
    # Stop and Exit
    # 如果用户自定义脚本列表不存在，则该脚本终止
    logger -st "($(basename $0))" $$ "***** UNABLE TO LOCATE LIST OF USER'S CUSTOM SCRIPTS *****"
    logger -st "($(basename $0))" $$ "***** EXIT *****"
    exit 2
fi
