#!/bin/sh
#
# 此脚本用于卸载“华硕路由器官方固件&梅林固件开机自动运行脚本系统”
#
# 使用nvram对变量script_usbmount进行设置，将其恢复为默认状态
nvram unset script_usbmount
#
# 使用nvram对变量script_usbumount进行设置，将其恢复为默认状态
nvram unset script_usbumount
#
# Commit the changes
# 使用nvram命令对路由器进行设置后，必须执行nvram commit命令，才能将已作出的修改保存至路由器
nvram commit
#
# Reboot the router
# 需使用reboot命令重启路由器，设置才能生效
reboot
