#!/bin/sh
#
# 此脚本为用户自定义脚本列表，可按使用需求修改第17-31行
#
########## SET THE CUSTOM VARIABLES ##########
#
# 设置自定义变量
# 当该程序运行结束，此处设置的变量自动取消
#
# USB_PATH: The mount point of the USB flash drive
# 设置自定义变量USB_PATH为U盘挂载点
USB_PATH=$(nvram get script_usbmount | awk -F / '{print "/"$2"/"$3"/"$4}')
#
########## END ##########
#
#
########## LIST OF USER'S CUSTOM SCRIPTS ##########
#
# 用户自定义脚本列表（遵循下述格式）
#
# 脚本名
# 可执行脚本文件的绝对路径
#
# 例如：
# SOFTWARE SERVICE（使用时，删除下一行行首的#）
#${USB_PATH}/script_bootloader/user_scripts/software/software.service
#
# NEXT SERVICE
#${USB_PATH}/script_bootloader/user_scripts/
#
########## END ##########
#
#
logger -st "($(basename $0))" $$ "***** ALL THE USER'S CUSTOM SCRIPTS HAVE BEEN LOADED SUCCESSFULLY *****"