#!/bin/sh
#
# 此脚本为用户自定义脚本列表，可按使用需求修改第17-31行
#
########## SET THE CUSTOM ENVIRONMENT VARIABLES ##########
#
# 设置自定义环境变量（本例中，该环境变量为ADMINUSER）
#
# ADMINUSER: The administrator of the router
# 设置环境变量ADMINUSER为路由器管理页面的登陆帐号（本例中，帐号为routeradmin）
logger -st "($(basename $0))" $$ "***** SET CUSTOM ENVIRONMENT VARIABLES *****"
export ADMINUSER='routeradmin'
#
########## END ##########
#
#
########## LIST OF USER'S CUSTOM SCRIPTS ##########
#
# 用户自定义脚本列表（遵循下述格式）
#
# 脚本名
# 可执行脚本文件的绝对路径
#
# 例如：
# SOFTWARE SERVICE（使用时，删除下一行行首的#）
#/tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/software/software.service
#
# SWAP_ENABLE SERVICE
#/tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/swap/swap_enable.service
#
# NEXT SERVICE
#/tmp/mnt/ASUS_ROUTER/script_bootloader/user_scripts/
#
########## END ##########
#
#
########## UNSET THE CUSTOM ENVIRONMENT VARIABLES ##########
#
# 当所有用户自定义脚本加载后，取消自定义环境变量ADMINUSER
#
logger -st "($(basename $0))" $$ "***** UNSET CUSTOM ENVIRONMENT VARIABLES *****"
unset ADMINUSER
#
########## END ##########
#
#
logger -st "($(basename $0))" $$ "***** ALL THE USER'S CUSTOM SCRIPTS HAVE BEEN LOADED SUCCESSFULLY *****"
