#!/bin/sh
#
logger -st "($(basename $0))" $$ "*--------- ENTWARE FOR ASUS ROUTER INSTALLATION ---------*"
#
########## INSTALLATION CONFIGURATION ##########
#
# Check type of the ASUS Router
# 检查华硕路由器型号
router_type=$(uname -m)
#
########## END ##########
#
#
########## INSTALL ENTWARE ##########
#
# Install Entware according to the type of the ASUS Router
# 根据路由器型号，安装适当版本的Entware
if [ $router_type == 'armv7l' ]
then
    wget -O - http://bin.entware.net/armv7sf-k2.6/installer/generic.sh | sh
fi
#
if [ $router_type == 'aarch64' ]
then
    wget -O - http://bin.entware.net/aarch64-k3.10/installer/generic.sh | sh
fi
#
if [ $router_type == 'mips' ]
then
    wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh
fi
#
########## END ##########
#
#
########## COPY HOME ##########
#
logger -st "($(basename $0))" $$ "*--------- COPY HOME TO USB FLASH DRIVE ---------*"
#
# Check if HOME is already in the USB flash drive
# 检查目录/tmp/mnt/ASUS_ROUTER/home/root/是否存在
if [ ! -d '/tmp/mnt/ASUS_ROUTER/home/root/' ]
then
    # Copy /tmp/home/root to /tmp/mnt/ASUS_ROUTER/home/
    # 如果目录/tmp/mnt/ASUS_ROUTER/home/root/不存在，则执行
    cp -R /tmp/home/root /tmp/mnt/ASUS_ROUTER/home/
    logger -st "($(basename $0))" $$ "***** HOME HAS BEEN COPIED *****"
    #
else
    # Do nothing but prompt the user
    # 如果目录/tmp/mnt/ASUS_ROUTER/home/root/存在，则执行
    logger -st "($(basename $0))" $$ "***** HOME EXISTS *****"
fi
reboot
#
########## END ##########