#!/bin/sh
#
logger -st "($(basename $0))" $$ "*--------- ENTWARE FOR ASUS ROUTER INSTALLATION ---------*"
#
########## SET THE CUSTOM VARIABLES ##########
#
# 设置自定义变量
# 当该程序运行结束，此处设置的变量自动取消
#
# USB_PATH: The mount point of the USB flash drive
# 设置自定义变量USB_PATH为U盘挂载点
USB_PATH=$(nvram get script_usbmount | awk -F / '{print "/"$2"/"$3"/"$4}')
#
########## END ##########
#
#
########## INSTALLATION CONFIGURATION ##########
#
# Check type of the ASUS Router
# 检查华硕路由器架构
router_type=$(uname -m)
#
########## END ##########
#
#
########## INSTALL ENTWARE ##########
#
# Install Entware according to the type of the ASUS Router
# 根据路由器架构，自动安装适当版本的Entware
if [ ${router_type} == "armv7l" ]
then
    wget -O - http://bin.entware.net/armv7sf-k2.6/installer/generic.sh | sh
fi
#
if [ ${router_type} == "aarch64" ]
then
    wget -O - http://bin.entware.net/aarch64-k3.10/installer/generic.sh | sh
fi
#
if [ ${router_type} == "mips" ]
then
    wget -O - http://pkg.entware.net/binaries/mipsel/installer/installer.sh | sh
fi
#
########## END ##########
#
#
########## COPY HOME ##########
#
logger -st "($(basename $0))" $$ "*--------- COPY HOME TO USB FLASH DRIVE ---------*"
#
# Check if HOME is already in the USB flash drive
# 检查目录${USB_PATH}/home/root/是否存在
if [ ! -d "${USB_PATH}/home/root/" ]
then
    # Copy /tmp/home/root to ${USB_PATH}/home/
    # 如果目录${USB_PATH}/home/root/不存在，则执行
    cp -R /tmp/home/root ${USB_PATH}/home/
    logger -st "($(basename $0))" $$ "***** HOME HAS BEEN COPIED *****"
    #
else
    # Do nothing but prompt the user
    # 如果目录${USB_PATH}/home/root/存在，则执行
    logger -st "($(basename $0))" $$ "***** HOME EXISTS *****"
fi
reboot
#
########## END ##########