#!/bin/sh
#
# 此脚本用于安装“华硕路由器开机自动运行脚本系统”
#
logger -st "($(basename $0))" $$ "*--------- SCRIPTS BOOTLOADER FOR ASUS ROUTER INSTALLATION ---------*"
#
########## SET THE CUSTOM VARIABLES ##########
#
# 设置自定义变量
# 当该程序运行结束，此处设置的变量自动取消
#
# USB_PATH: The mount point of the USB flash drive
# 设置自定义变量USB_PATH为U盘挂载点
USB_PATH=$(find / -name 'script_bootloader' | awk -F / '{print "/"$2"/"$3"/"$4}')
#
########## END ##########
#
#
########## ROUTER CONFIGURATION ##########
#
# Check if ${USB_PATH}/script_bootloader/script_bootloader_usb_mount and ${USB_PATH}/script_bootloader/script_bootloader_usb_umount exist
# 检查文件${USB_PATH}/script_bootloader/script_bootloader_usb_mount和${USB_PATH}/script_bootloader/script_bootloader_usb_umount是否存在
if [ -e "${USB_PATH}/script_bootloader/script_bootloader_usb_mount" ] && [ -e "${USB_PATH}/script_bootloader/script_bootloader_usb_umount" ]
then
    logger -st "($(basename $0))" $$ "***** ALL THE ESSENTIAL FILES EXIST *****"
    logger -st "($(basename $0))" $$ "***** SETTING THE ROUTER *****"
    #
    # Set nvram variable "script_usbmount" and "script_usbumount"
    # 如果两个文件都存在，则设置nvram变量script_usbmount和script_usbumount
    #
    # When the USB flash drive is mounted, the script "script_bootloader_usb_mount" will run automatically
    # 当U盘被挂载后，脚本script_bootloader_usb_mount会自动运行
    # 使用nvram对变量script_usbmount进行设置。当U盘被挂载后，任何被该变量引用的可执行脚本会自动执行。本例中，设置该变量引用脚本${USB_PATH}/script_bootloader/script_bootloader_usb_mount
    nvram set script_usbmount="${USB_PATH}/script_bootloader/script_bootloader_usb_mount"
    #
    # When the USB flash drive is unmounted, the script "script_bootloader_usb_umount" will run automatically
    # 当U盘被卸载前，脚本script_bootloader_usb_umount会自动运行
    # 使用nvram对变量script_usbumount进行设置。当U盘被卸载前，任何被该变量引用的可执行脚本会自动执行。本例中，设置该变量引用脚本${USB_PATH}/script_bootloader/script_bootloader_usb_umount
    nvram set script_usbumount="${USB_PATH}/script_bootloader/script_bootloader_usb_umount"
    #
    # Commit the changes
    # 使用nvram命令对路由器进行设置后，必须执行nvram commit命令，才能将已作出的修改保存至路由器
    nvram commit
    logger -st "($(basename $0))" $$ "***** INSTALLATION HAS BEEN COMPLETE *****"
    #
    # Reboot the router
    # 需使用reboot命令重启路由器，确保设置生效
    logger -st "($(basename $0))" $$ "***** REBOOTING THE ROUTER *****"
    reboot
    #
else
    # Stop and Exit
    # 如果两个文件不同时存在，则该脚本终止
    logger -st "($(basename $0))" $$ "***** UNABLE TO LOCATE THE ESSENTIAL FILES *****"
    logger -st "($(basename $0))" $$ "***** INSTALLATION HAS NOT BEEN COMPLETE *****"
    logger -st "($(basename $0))" $$ "***** EXIT *****"
    exit 1
fi
#
########## END ##########