#!/bin/sh
#
# 此脚本在卸载U盘前，强制结束从U盘中加载的可执行程序的进程，并消除Entware运行环境，防止卸载U盘失败
#
logger -st "($(basename $0))" $$ "***** UMOUNT THE USB FLASH DRIVE *****"
#
########## KILL ALL THE RELEVANT PROCESSES ##########
#
logger -st "($(basename $0))" $$ "***** KILL ALL THE RELEVANT PROCESSES *****"
#
# Kill all the relevant processes
# 结束全部从U盘中加载的可执行程序的进程（本例中，该可执行程序为/tmp/mnt/sda1/script_bootloader/usr/software/software）
#
# Kill /tmp/mnt/sda1/script_bootloader/usr/software/software
# 结束进程/tmp/mnt/sda1/script_bootloader/usr/software/software，使用时，删除下一行行首的#
#ps | grep "/tmp/mnt/sda1/script_bootloader/usr/software/software" | grep -v 'grep' | awk '{print $1}' | xargs kill
# Kill next process
# 结束下一个进程XXXXX（假定该可执行程序为/tmp/mnt/sda1/script_bootloader/usr/XXXXX/XXXXX），使用时，删除下一行行首的#
#ps | grep "/tmp/mnt/sda1/script_bootloader/usr/XXXXX/XXXXX" | grep -v 'grep' | awk '{print $1}' | xargs kill
#
logger -st "($(basename $0))" $$ "***** ALL THE RELEVANT PROCESSES HAVE BEEN KILLED *****"
#
########## END ##########
#
#
########## DISABLE ENTWARE ##########
#
# Check if /opt/etc/init.d/rc.unslung exists
# 检查文件/opt/etc/init.d/rc.unslung是否存在
if [ -e '/opt/etc/init.d/rc.unslung' ]
then
    # Stop /opt/etc/init.d/rc.unslung
    # 如果文件/opt/etc/init.d/rc.unslung存在，则执行
    /opt/etc/init.d/rc.unslung stop
    logger -st "($(basename $0))" $$ "***** ENTWARE HAS BEEN DISABLED *****"
    #
else
    # Stop and Exit
    # 如果文件/opt/etc/init.d/rc.unslung不存在，则该脚本终止
    logger -st "($(basename $0))" $$ "***** ENTWARE CAN NOT BE DISABLED *****"
    logger -st "($(basename $0))" $$ "***** EXIT *****"
    exit 1
fi
#
########## END ##########