#!/bin/sh
#
# 此脚本用于卸载“华硕路由器开机自动运行脚本系统”
#
logger -st "($(basename $0))" $$ "*--------- SCRIPTS BOOTLOADER FOR ASUS ROUTER UNINSTALLATION ---------*"
#
########## SET THE CUSTOM VARIABLES ##########
#
# 设置自定义变量
# 当该程序运行结束，此处设置的变量自动取消
#
# USB_PATH: The mount point of the USB flash drive
# 设置自定义变量USB_PATH为U盘挂载点
USB_PATH=$(nvram get script_usbmount | awk -F / '{print "/"$2"/"$3"/"$4}')
#
########## END ##########
#
#
########## TERMINATE ANYTHING RELATED ##########
#
# Load ${USB_PATH}/script_bootloader/script_bootloader_usb_umount
# 执行文件${USB_PATH}/script_bootloader/script_bootloader_usb_umount
${USB_PATH}/script_bootloader/script_bootloader_usb_umount
logger -st "($(basename $0))" $$ "***** ANYTHING RELATED HAS BEEN TERMINATED *****"
#
########## END ##########
#
#
########## ROUTER CONFIGURATION ##########
#
logger -st "($(basename $0))" $$ "***** RESTORE ASUS ROUTER SETTINGS *****"
#
# When the USB flash drive is mounted, nothing will run automatically
# 使用nvram对变量script_usbmount进行设置，将其恢复为默认状态
nvram unset script_usbmount
#
# When the USB flash drive is unmounted, nothing will run automatically
# 使用nvram对变量script_usbumount进行设置，将其恢复为默认状态
nvram unset script_usbumount
#
# Commit the changes
# 使用nvram命令对路由器进行设置后，必须执行nvram commit命令，才能将已作出的修改保存至路由器
nvram commit
#
# Reboot the router
# 需使用reboot命令重启路由器，确保设置生效
reboot
#
########## END ##########