#!/bin/sh
#
# 此程序用于修改现有环境，以适应系统级更新
#
########## SET THE CUSTOM VARIABLES ##########
#
# 设置自定义变量
# 当该程序运行结束，此处设置的变量自动取消
#
# USB_MOUNT_POINT: The mount point of the USB flash drive
# 设置自定义变量USB_MOUNT_POINT为U盘挂载点
USB_MOUNT_POINT="$(nvram get script_usbmount | /opt/bin/sed 's/\/script_bootloader.*//')"
#
# ENTWARE_ETC: The directory which contains all the configuration files installed by Entware
# 设置自定义变量ENTWARE_ETC为Entware安装的配置文件目录
ENTWARE_ETC="${USB_MOUNT_POINT}/etc"
#
# ENTWARE_DNSMASQD: The directory which contains all the configuration files used by dnsmasq
# 设置自定义变量ENTWARE_DNSMASQD为dnsmasq配置文件目录
ENTWARE_DNSMASQD="${ENTWARE_ETC}/dnsmasq.d"
#
# ENTWARE_FWD: The directory which contains all the configuration files used by fwd
# 设置自定义变量ENTWARE_FWD为fwd配置文件目录
ENTWARE_FWD="${ENTWARE_ETC}/fw.d"
#
# ENTWARE_MONITD: The directory which contains all the configuration files used by monit
# 设置自定义变量ENTWARE_MONITD为monit配置文件目录
ENTWARE_MONITD="${ENTWARE_ETC}/monit.d"
#
# SBL_SYS_ROOT: The root directory for SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
# 设置自定义变量SBL_SYS_ROOT为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统根目录
SBL_SYS_ROOT="${USB_MOUNT_POINT}/script_bootloader"
#
# SBL_SYS_BIN: The directory which contains all the executable files related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
# 设置自定义变量SBL_SYS_BIN为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统可执行文件目录
SBL_SYS_BIN="${SBL_SYS_ROOT}/bin"
#
# SBL_SYS_ETC: The directory which contains all the configuration files related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
# 设置自定义变量SBL_SYS_ETC为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统配置文件目录
SBL_SYS_ETC="${SBL_SYS_ROOT}/etc"
#
# SBL_SYS_TMP: The directory which contains all the temporary files related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
# 设置自定义变量SBL_SYS_TMP为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统临时文件目录
SBL_SYS_TMP="${SBL_SYS_ROOT}/tmp"
#
# SBL_SYS_USR: The directory which contains all the external software resources (add-ons) related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
# 设置自定义变量SBL_SYS_USR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统外部软件资源目录，即插件目录
SBL_SYS_USR="${SBL_SYS_ROOT}/usr"
#
# SBL_SYS_VAR: The directory which contains all the variable files related to SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER
# 设置自定义变量SBL_SYS_VAR为SCRIPTS-BOOTLOADER-FOR-ASUS-ROUTER系统可变文件目录
SBL_SYS_VAR="${SBL_SYS_ROOT}/var"
#
########## END ##########
#
#
########## LOAD FUNCTIONS ##########
#
#
########## END ##########
#
#
########## PATCH SYSTEM ##########
#
##### DNSMASQ.D #####
# Configure monit
# 配置monit
/opt/bin/rm -f "${ENTWARE_MONITD}/dnsmasq.d"
/opt/bin/rm -f "${ENTWARE_MONITD}/dnsmasq.d.on"
/opt/bin/cp -f "/opt/script_bootloader/usr/dnsmasq.d/etc/monit.d/dnsmasq.d" "${ENTWARE_MONITD}"
/opt/bin/chmod 600 "${ENTWARE_MONITD}/dnsmasq.d"
/opt/bin/mv -f "${ENTWARE_MONITD}/dnsmasq.d" "${ENTWARE_MONITD}/dnsmasq.d.on"
#
##### Adguard-Home #####
# Configure dnsmasq.d
# 配置dnsmasq.d
if [ ! -d "/opt/script_bootloader/usr/adguardhome/etc/dnsmasq.d" ]
then
    /opt/bin/mkdir "/opt/script_bootloader/usr/adguardhome/etc/dnsmasq.d"
fi
#
/opt/bin/echo -e "server=127.0.0.1#2153" > "/opt/script_bootloader/usr/adguardhome/etc/dnsmasq.d/adguardhome.conf"
#
##### ShadowSocks #####
# Configure monit
# 配置monit
if [ -e "${ENTWARE_MONITD}/ss_local" ] || [ -e "${ENTWARE_MONITD}/ss_local.on" ]
then
    /opt/bin/monit stop "SS_TRANSPARENT_PROXY_OVERTURE" > /dev/null 2>&1
    #
    /opt/bin/rm -f "${ENTWARE_MONITD}/ss_transparent_proxy_overture_prog"
    /opt/bin/rm -f "${ENTWARE_MONITD}/ss_transparent_proxy_overture_prog.on"
    /opt/bin/rm -f "${ENTWARE_MONITD}/ss_transparent_proxy_overture_file"
    /opt/bin/rm -f "${ENTWARE_MONITD}/ss_transparent_proxy_overture_file.on"
    #
    /opt/bin/cp -f "/opt/script_bootloader/usr/shadowsocks/etc/monit.d/ss_transparent_proxy_overture_file" "${ENTWARE_MONITD}"
    /opt/bin/chmod 600 "${ENTWARE_MONITD}/ss_transparent_proxy_overture_file"
    /opt/bin/mv -f "${ENTWARE_MONITD}/ss_transparent_proxy_overture_file" "${ENTWARE_MONITD}/ss_transparent_proxy_overture_file.on"
    #
    /opt/bin/cp -f "/opt/script_bootloader/usr/shadowsocks/etc/monit.d/ss_transparent_proxy_without_dns_file" "${ENTWARE_MONITD}"
    /opt/bin/chmod 600 "${ENTWARE_MONITD}/ss_transparent_proxy_without_dns_file"
    #/opt/bin/mv -f "${ENTWARE_MONITD}/ss_transparent_proxy_without_dns_file" "${ENTWARE_MONITD}/ss_transparent_proxy_without_dns_file.on"
    #
fi
/opt/bin/monit reload
/opt/bin/sleep 30
cd /tmp
/tmp/sbl_restart_router
#
########## END ##########